services:
  - type: web
    name: employee-panel
    runtime: node
    plan: starter
    repo: https://github.com/HAFIZFARHAN630/employee-Panel-ClickTake
    branch: main
    buildCommand: |
      npm install -g bun
      bun install
      bunx prisma generate
      npx next build
      cp -r .next/static .next/standalone/.next/
      cp -r public .next/standalone/
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:cTM5%3FZuqCsYk7-5@db.ggicuqmpkveegsjgmcvc.supabase.co:5432/postgres?sslmode=require
      - key: JWT_SECRET
        value: f9c7e16e424084754f272f9a00b87fc25d7ece1c7730fee2fbd446f5294dc3e3
      - key: CLOUDINARY_CLOUD_NAME
        value: dwioesu97
      - key: CLOUDINARY_API_KEY
        value: "641277517839454"
      - key: CLOUDINARY_API_SECRET
        value: m55dleAgSVsQqWbQBSaQgbyvoHw
      - key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
        value: dwioesu97
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: AIzaSyC2pGU-k-1pui7VwIp1mDy47P_Y87V7DYo
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: panel-clicktake.firebaseapp.com
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: panel-clicktake
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: panel-clicktake.firebasestorage.app
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: "446300805588"
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: "1:446300805588:web:8347a1e6ee79c3a8a69e41"
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        value: G-NBEKLP05GV
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://ggicuqmpkveegsjgmcvc.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnaWN1cW1wa3ZlZWdzamdtY3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyMjMxMDgsImV4cCI6MjA5Nzc5OTEwOH0.c8qTfunvdONX5JWQ5mJrLY4UTAy13hN1CoRAOdZAU7w
      - key: NEXT_PUBLIC_BASE_URL
        value: https://panel-clicktake.web.app